### ISSUE TITLE
Research and document current OS branding

### ISSUE THREAD

**Issue by BruceP99166** [openstax/ux#76]
# Description
As a product team member I want a current guideline for OS branding to be published so that I can incorporate approved branding during feature development and maintenance.

# Acceptance Criteria
- ~~A current guideline for OpenStax branding is published.~~
- [x] Pattern library has been updated with current OS styles for the quarter
- [x] Pattern library has been made designer-friendly
- [ ] Accessibility recommendations for the quarter have been implemented (Q3)

**Comment by victoria-cooke** [comment]
**Updated Pattern Library**
[20190703_UX_PatternLibrary_VCooke_v16-01](https://drive.google.com/file/d/1DibeT-2zg9mHWQ9f8g_Sf6U9hzEx8meL/view?usp=sharing)

I recommend phasing out v15 and using v16 on totally new projects.

**Changes**
- Added infographics section
- Added icons section
- Added gradients in colors section
- Cleaned up type styles
- Cleaned up layer styles
- Added colors as layer styles so that they’re adjustable
- Converted components to symbols for easy access/use
- Symbols updated to be responsive
- Added dynamic icons when possible so that they can be easily edited
- Updated underlined text to be dynamic (capability was previously unavailable)
- Fleshed out the atomic design on symbols so that more detailed changes can be made while reducing the number of necessary symbols
- Added text and layer styles to library page components so that the application is visible
- Added mobile components for certain symbols
- Added dynamic images to symbols
- Restructured symbols and pages

**Comment by victoria-cooke** [comment]
@andymuddimer Let me know if you have any questions when updating the KD doc.
